### PR TITLE
Support for Doom 2 RPG and Wolfenstein RPG

### PR DESCRIPTION
**Pull request by alborrajo**

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
I cherry-picked 11a85aa3271e71bce245a125d99081ed860c4278 to trunk as d61580584f578ec2a76e1a207261e03c15fb5910 since I needed it for something. (I'll look at the rest eventually.)

**Comment by klaxons1** [comment]
@alborrajo can you please provide build for windows with that commits?

**Comment by hikari-no-yume** [comment]
GitHub will generate one in about twenty minutes' time.

**Comment by klaxons1** [comment]
Thank you, @hikari-no-yume !

**Comment by hikari-no-yume** [comment]
Looks like the Windows build failed due to an issue with the code in this pull request.

**Comment by klaxons1** [comment]
Ah, it's bad then.

**Comment by klaxons1** [comment]
image
WOW

**Comment by hikari-no-yume** [comment]
@klaxons1 check out how it looks with the scale hack :)

**Comment by klaxons1** [comment]
image
2x, cant choose more because the window is creates out of the screen

**Comment by hikari-no-yume** [comment]
> cant choose more because the window is creates out of the screen

Ah yeah I've had that problem before. I ended up using some weird tool for window resizing in order to snap the window into the right place. The full-screen mode is often better.

**Comment by klaxons1** [comment]
image
wolfenstein rpg works too

**Comment by klaxons1** [comment]
image
not a problem, but it seems touchhle prefers to use igpu instead of discrete on laptops.

**Comment by hikari-no-yume** [comment]
> it seems touchhle prefers to use igpu instead of discrete on laptops

Oh, I'd never thought about that because I don't have a laptop with a dGPU. I guess I could eventually add an option for it, but considering we're dealing with 15-year-old mobile games here, I doubt most people's iGPUs are going to have problems with it. It would be kinda wasteful with power usage to use the dGPU for this.

**Comment by windwakr** [comment]
>cant choose more because the window is creates out of the screen
You can shift+right click the game window in the task bar and choose the move options. Your cursor will jump to the window and change to a 4-way arrow. Use the arrow keys on your keyboard to move the window.

Alternatively, you can right click an empty spot of the taskbar and choose the "cascade windows" option. Note that this will move and resize all of your open windows.

**Comment by hikari-no-yume** [comment]
Thanks so much for telling me about the shift modifier! I've tried to get at that menu through the task bar before and it never worked, I guess shift is the secret.

**Comment by windwakr** [comment]
The second area in Doom 2 RPG renders entirely black.

Untitled

Save file
[doom2rpgsave.zip](https://github.com/hikari-no-yume/touchHLE/files/12443948/doom2rpgsave.zip)

**Comment by alborrajo** [comment]
imagen
It seems to render correctly on Mac but not on Windows or Android

**Comment by Thetouchedjoe** [comment]
ok, youre guys are really really awesome to make games simply added to the touchHLE, can play Doom 2 and Wolfenstein RPG make me joking, "wow theyre seemly a hardworker"

**Comment by Jaffhj** [comment]
Ok?

**Comment by hikari-no-yume** [comment]
In case anyone was following the pull request to get updates: the support was merged and it's in https://github.com/hikari-no-yume/touchHLE/releases/tag/v0.2.1.

**Pull request closed without merging**
