### PR TITLE
Solitaire Top 3 by Posisoft: Bring from Nothing to Menus.

### PR DESCRIPTION
**Pull request by Skryptonyte**
This PR brings the game to the menus. However it doesn't reach gameplay. This app requires way too many unimplemented UIKit stuff to function so I've just focused on bringing it into the menus for now which should be a general improvement in UIKit compatibility across the board.

Only issue I am seeing is scrolling is very sluggish.

image
image

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
Oh, fantastic, this is all stuff that I had been thinking of implementing but never got round to. Thank you! I'll review it sometime this week.

**Comment by hikari-no-yume** [comment]
If you would like access to the developer Discord rooms, send me an email to my git email address.

**Comment by ciciplusplus** [comment]
Hello @Skryptonyte, do you plan to follow up on this one? thanks

**Comment by omagadsamsa** [comment]
listing no work, its crashing

**Comment by ciciplusplus** [comment]
Merged as of 47a71327e0bf4df703d1c39059363eac214d4cf0 with some modifications and fixes.

Thanks for your contribution!

**Pull request closed without merging**
