### PR TITLE
Support for KataDama a.k.a "I love Katamari"

### PR DESCRIPTION
**Pull request by ciciplusplus**
### Tested versions
- 1.0.0
- 1.0.2

### Known issues
- Game has tilt controls so either controller or a tilt device is required to play
- 1.0.0 has some audio issues
- Only English localization is supported
- "More Namco games" section is crashing
- Scale hack is working but with minor issues (e.g. round corners have artifacts)

### Screenshots
F3Z7_m4WcAEwPM-
F3Z74HLWgAEYOKA
F3Z72sIXwAAqD9v
F3Z7yTQWYAAY2bI

### CODE REVIEW

**Comment by sheva22222** [comment]
Bubble Bash Launched by Gameloft
Снимок экрана 2023-09-01 205731

**Comment by ciciplusplus** [comment]
> Bubble Bash Launched by Gameloft Снимок экрана 2023-09-01 205731

This game was already reported as partially playable before https://github.com/hikari-no-yume/touchHLE/issues/115.
Otherwise, please don't comment on unrelated issues to this PR. At best, open an another one, if it's not duplicated.

**Comment by hikari-no-yume** [comment]
Comments deleted which reference a pirate site. Sorry.

**Comment by ciciplusplus** [comment]
Closing as most commits were accepted and the game now works on the trunk

Reviews were done here https://review.gerrithub.io/q/topic:%22touchHLE/pull/146%22

**Pull request closed without merging**
