### PR TITLE
Castle of magic default options

### PR DESCRIPTION
**Pull request by gamelover-sergei**
My first works

### CODE REVIEW

**Comment by TouchHLEuser** [comment]
Good bro

**Comment by hikari-no-yume** [comment]
You have not tested this PR, this will crash touchHLE.

**Comment by gamelover-sergei** [comment]
> You have not tested this PR, this will crash touchHLE.

In my steam deck all works

**Comment by hikari-no-yume** [comment]
It crashes when launching Castle of Magic. You may have tested a similar patch on your Steam Deck, but you did not test *this* patch on your Steam Deck. We do not accept untested patches.

**Comment by ciciplusplus** [comment]
@gamelover-sergei Why do you think we should even review your PR from your repository where you're bad mouthing our project and calling us morons https://github.com/gamelover-sergei/touchHLE/commit/59581876f3dd2bce557483d55522e397bd11d473 ?

I'm banning you from this repository.

**Pull request closed without merging**
