### PR TITLE
Add GHA build

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/gliptak/touchHLE/actions/runs/4651782545

missed #93

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
Well, um, as you said…

> missed #93

This is a duplicate.

**Comment by gliptak** [comment]
kinda. this PR implements lint and also targets to have a build matrix for supported OSs

**Comment by hikari-no-yume** [comment]
Having linting would be nice to have for sure. I'm a bit confused by the build matrix though… it's not providing any benefit if there's only a single OS in it, and the build directions you've used will only work on that OS.

**Comment by gliptak** [comment]
for the build matrix, we can add linux and windows in follow PR and just have the OS specific steps different (removing duplication as compared to #93 )

**Comment by hikari-no-yume** [comment]
I'll consider it as a future improvement, I guess.

By the way, why do you install Boost twice?

**Comment by gliptak** [comment]
the lint job is independent from the matrixed relerase_build jobs

**Pull request closed without merging**
