### PR TITLE
Rayman 2

### PR DESCRIPTION
**Pull request by ciciplusplus**
### Tested versions
- 1.0.1

### Known issues
- No music :'(
- Version 1.0.2 is crashing
- Selecting 'More games' is crashing
- Selecting Japanese language crash-loop the game

### Notes
- ~~Mutlti-touch is kinda required to play (but done [here](https://github.com/hikari-no-yume/touchHLE/pull/161) ;) )~~
- I was able to finish tutorial and 5 first levels on Android during tests
- ~~FPS are uncapped~~

### Screenshots
Screenshot 2023-10-08 at 01 24 22
Screenshot 2023-10-08 at 16 20 12

### CODE REVIEW

**Comment by Jaffhj** [comment]
Is Works Only Version 1.0.1 for Rayman 2

**Comment by AEDOODLEDASHMAKE** [comment]
2010-2013 rayman 2 will Closed App Store

**Comment by sheva2281** [comment]
com.gameloft.rayman2free-iOS2.2.1-(Clutch-2.0.4) work

**Comment by Jaffhj** [comment]
Yes???

**Comment by nighto** [comment]
@sheva2281 not sure if it was a a statement or a question, assuming it was a question: this PR is still open, you can either fetch that specific version from the contributor and build it yourself or wait for the PR to be picked up by the maintainer.

**Pull request merged**
