### PR TITLE
Implement multiple functions for Spore

### PR DESCRIPTION
**Pull request by teromene**
This brings Spore version `1.0.64` to a running state.

### CODE REVIEW

**Comment by omagadsamsa** [comment]
go action in fork?

**Comment by hikari-no-yume** [comment]
This is an interesting PR, does the game work fully for you? I have my own set of hacky patches that get Spore: Origins running, but it crashes after finishing the tutorial.

**Comment by teromene** [comment]
It crashes on null-page access after modifying the creature for the first time

**Comment by omagadsamsa** [comment]
> This is an interesting PR, does the game work fully for you? I have my own set of hacky patches that get Spore: Origins running, but it crashes after finishing the tutorial.

washes the build as it seems the issue is resolved?

**Comment by hikari-no-yume** [comment]
Oh okay, so you've hit the same problem I did. I was probably using an older version of Spore: Origins that doesn't need quite as many functions.

**Comment by ciciplusplus** [comment]
Hello @teromene ,

Please follow this guide https://github.com/hikari-no-yume/touchHLE/blob/trunk/CONTRIBUTING.md if you want to contribute.

In particular:

- you should push your commits to Gerrithub with Change-Ids
- please abide to https://github.com/hikari-no-yume/touchHLE/blob/trunk/dev-docs/code-style.md
- please separate your PR to smaller commits. You could group them by functionality or API implementation

Thanks

**Comment by teromene** [comment]
Done. I have submitted my changes to gerrit

**Comment by omagadsamsa** [comment]
hmm, you can skip the tutorial in the settings but there are bugs, it always moves to the top, I saw this in old versions of Super Monkey Ball, I’ve just completed the first level and now I’m going to go through all the levels

> This is an interesting PR, does the game work fully for you? I have my own set of hacky patches that get Spore: Origins running, but it crashes after finishing the tutorial.

**Comment by omagadsamsa** [comment]
even when you lose the game and go into the character editor and when you do something the game crashes

**Comment by omagadsamsa** [comment]
image
WHY IT WORKS

**Comment by ciciplusplus** [comment]
@teromene please email me at my git email address if you want access to the developer Discord server

**Comment by omagadsamsa** [comment]
Level 5 impossible https://youtu.be/zUygyJfaFRU

**Comment by omagadsamsa** [comment]
omg in Android build ACELEMETR work

**Comment by makaher** [comment]
close pr, spore work in touchhle trunk

**Comment by ciciplusplus** [comment]
> close pr, spore work in touchhle trunk

It is not, it's crashing after a tutorial.

Please stop creating noise in the different issues/PRs, otherwise I'll ban you for a week.

**Comment by makaher** [comment]
> > close pr, spore work in touchhle trunk
> 
> It is not, it's crashing after a tutorial.
> 
> Please stop creating noise in the different issues/PRs, otherwise I'll ban you for a week.

its in teromene trunk and in touchhle original trunk

**Comment by hikari-no-yume** [comment]
Please understand that only touchHLE trunk is official.

**Comment by makaher** [comment]
> Please understand that only touchHLE trunk is official.

In this pull request, everything is the same as in the official one, it does not develop and the game works the same as in the original touchhole

**Comment by marcosemuladores** [comment]
Test Spore 1.0

**Comment by ciciplusplus** [comment]
As of https://github.com/touchHLE/touchHLE/commit/2f5a1ead9144bb83dba836f738da7116bcfbb169 Spore is now working on the trunk without major issues.

Most of commits from this PR were already merged with small modifications. Closing it for now.

Sorry it took so long.

**Comment by marcosemuladores** [comment]
Thanks

Em ter., 5 de nov. de 2024, 10:05, ciciplusplus ***@***.***>
escreveu:

**Pull request closed without merging**
