### PR TITLE
Earthworm Jim

### PR DESCRIPTION
**Pull request by ciciplusplus**
### Tested versions
- 1.0.8

### Known issues
- In-game splash screens are not properly rendering "dim" state
- Level select screen have rendering issues
- Music support is in WIP state

Note: this is on top of fifa-10 branch/PR

### Screenshots

Screenshot 2024-01-11 at 00 16 56
Screenshot 2024-01-11 at 00 17 19

### CODE REVIEW

**Comment by omagadsamsa** [comment]
Another bug: Japanese doesn't work, English replaces it

**Comment by omagadsamsa** [comment]
and after some time spent in the menu with the Japanese application crashes

**Comment by omagadsamsa** [comment]
even with the Japanese language when you are already playing you kill a cow and then you hit the tires and climb on the excavator and it crashes

**Comment by ciciplusplus** [comment]
> and after some time spent in the menu with the Japanese application crashes

do you have a crash stack?

**Comment by omagadsamsa** [comment]
> do you have a crash stack?

I don’t know what it is but I’ll record a video of how it happens

**Comment by omagadsamsa** [comment]
after departure from the menu, I recommend rewinding to the end of the video, there is a departure https://youtu.be/zD9XtBqtsVo

**Comment by ciciplusplus** [comment]
Thanks. The crash stack is a last lines of text printed in your command line window, usually starting with something like `thread 'main' panicked at ...` (next time you can just copy past it instead of recording the whole video).

I fixed the crash, but there is still an issue with background audio - tracks played only once instead of being played in the loop.

**Comment by omagadsamsa** [comment]
> Thanks. The crash stack is a last lines of text printed in your command line window, usually starting with something like `thread 'main' panicked at ...` (next time you can just copy past it instead of recording the whole video).
> 
> I fixed the crash, but there is still an issue with background audio - tracks played only once instead of being played in the loop.

Okay, thanks for seeing the app problem and fixing the crash!

**Comment by ciciplusplus** [comment]
Mostly merged, the game is now playable on the trunk. Background music is not supported as of now.
Closing

**Pull request closed without merging**
