### PR TITLE
Add alternatives section

### PR DESCRIPTION
**Pull request by upintheairsheep**
I've made it better than my last one

### CODE REVIEW

**Comment by nighto** [comment]
Typo: it should be `ALTERNATIVES.md` :)

**Comment by upintheairsheep** [comment]
> Typo: it should be `ALTERNATIVES.md` :)

I apologize

**Comment by WhyToFly** [comment]
This might also be worth considering: 
https://github.com/zydeco/aah
https://twitter.com/maczydeco/status/1155588054486310912

**Comment by hikari-no-yume** [comment]
I can't really justify why, and I know this is inconsistent with what I've said previously (sorry), but I don't feel like merging this. I do want to acknowledge the existence of other iOS emulation projects, but I don't feel like the README or this repo is the right place to do it.

**Pull request closed without merging**
