### PR TITLE
Add Github Action workflows for MacOS and Windows builds

### PR DESCRIPTION
**Pull request by dylanpdx**
This adds two Github Action jobs which build touchHLE and upload the results as an artifact. The uploaded artifact can be un-zipped and run just like a regular release, as I've included the `touchHLE_dylibs` and `touchHLE_fonts` directories.

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
Oh cool! I've never used GitHub's CI system before, I'm pleasantly surprised by how simple this script is.

Did you consider using the release prep script? I guess it might not work on Windows without git bash or something…

**Comment by hikari-no-yume** [comment]
Hmm, maybe it's good that it doesn't include everything that a full release has, though…

**Comment by dylanpdx** [comment]
> Did you consider using the release prep script? I guess it might not work on Windows without git bash or something…

I considered it, but wasn't sure if you would have preferred for me to differentiate it from a full release instead of a, 'pre-release' so to speak
I know the Windows runners do have Bash preinstalled so I think the release prep script *should* work, just a matter of installing pandoc and all that, but it shouldn't be an issue

**Comment by hikari-no-yume** [comment]
Hmm… I could modify the release script so it has a mode where it does a bare-minimum release: fonts, dylibs, default options, and license info, but no readmes.

But if that's the goal… what if the build artifacts would be just the executables? It would save space. You can just grab the other files from git after all, or from a full release.

**Comment by dylanpdx** [comment]
That could work! I hadn't considered just keeping the executables on their own, since originally my idea was for someone to be able to download an artifact, unzip it, and test the latest changes. Makes sense to save space though and since the extra files won't change, you could use the files from the last 'official' release. Should be a quick change if you prefer it like that!

**Comment by hikari-no-yume** [comment]
It saves me from having to maintain more than one list of files to go in releases, so I think I'd like it.

If it ends up being annoying, it can be changed later I suppose.

**Comment by hikari-no-yume** [comment]
Thanks, I'll play around with this later and then probably squash merge it. 👍

**Comment by hikari-no-yume** [comment]
Forgot about this, but it's merged now :)

**Pull request closed without merging**
